#ifndef PLAT_PERMISSION_GLOBAL_H
#define PLAT_PERMISSION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAT_PERMISSION_LIBRARY)
#  define PLAT_PERMISSION_EXPORT Q_DECL_EXPORT
#else
#  define PLAT_PERMISSION_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAT_PERMISSION_GLOBAL_H
