HEADERS+= $$PWD/ui/UI_Btn_Skin.h \
    $$PWD/ui/UI_Panel_BtnItemSetting.h \
    $$PWD/ui/UIYL_ChatAndCardPanel.h \
    $$PWD/ui/UIYL_CommonWordTreeSearchResultWidget.h \
    $$PWD/ui/UI_Panel_AddCommonWord.h \
    $$PWD/ui/UI_Panel_AddPersonalQuickCommonWord.h \
    $$PWD/ui/UI_Panel_ChangeSkin.h \
    $$PWD/ui/UI_Panel_HotKey.h \
    $$PWD/ui/UI_Panel_LemonLovesBeauty.h \
    $$PWD/ui/UI_Panel_ModifyCommonWord.h \
    $$PWD/ui/UI_Panel_OutputLog.h \
    $$PWD/ui/UI_Panel_PersonalQuickCommonWord.h \
    $$PWD/ui/UI_Panel_QuickCommonWord.h \
    $$PWD/ui/UI_Panel_RedEnvelopes.h \
    $$PWD/ui/UI_Pane_AI_Modify.h \
    $$PWD/ui/UI_Pane_AI_SelfBuild.h \
    $$PWD/ui/UI_Widget_CommonPhrasesCard_Panel.h \
    $$PWD/ui/UI_Widget_CommonWord_Panel.h \
    $$PWD/ui/UI_Wnd_AddPersonalQuickCommonWord.h \
    $$PWD/ui/UI_Wnd_HotKey.h \
    $$PWD/ui/UI_Wnd_ModifyCommonWord.h \
    $$PWD/ui/UI_Wnd_OutputLog.h \
    $$PWD/ui/UICardDataWidgetPanel.h \
    $$PWD/ui/UICardItemData.h \
    $$PWD/ui/UI_Pane_NewTab.h \
    $$PWD/ui/UI_Widget_AuxiliaryFun_Panenl.h \
    $$PWD/ui/UI_Widget_ChatTransfer.h \
    $$PWD/ui/UI_Widget_Statistics_BrokenNet_Panel.h \
    $$PWD/ui/UI_Widget_Statistics_Panel.h \
    $$PWD/ui/Robot/YL_ManRobotRuleListItem.h \
    $$PWD/ui/Robot/YL_ManRobotRuleLeafNodeItemData.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultWidget.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSetting_PreviewEffect_Widget.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingUrlWidget.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget_KeyPrompt.h \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget.h \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_CountPrompt.h \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_KeyPrompt.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListViewModel.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListView.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListViewItemDelegate.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListViewModel.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListView.h \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListViewItemDelegate.h \
    $$PWD/ui/Robot/UIEachBotMainWnd.h \
    $$PWD/ui/Robot/UIYL_EachbotSettingWidget.h \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListViewModel.h \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListView.h \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListViewItemDelegate.h \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_SearchResultWidget.h \
    $$PWD/ui/ListView/UIYL_CommonWordListTreeView.h \
    $$PWD/ui/ListView/UIYL_CommonWordListViewItemDelegate.h \
    $$PWD/ui/ListView/UIYL_CommonWordListViewModel.h \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListView.h \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListViewItemDelegate.h \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListViewItemModel.h \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListView.h \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListViewItemDelegate.h \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListViewItemModel.h \
    $$PWD/ui/TreeView/UI_TreeViewItemDelegate_CommonWord.h \
    $$PWD/ui/TreeView/UI_TreeViewItemModel_CommonWord.h \
    $$PWD/ui/TreeView/UI_TreeView_CommonWord.h \
    $$PWD/ui/UI_Wnd_OutputLog2.h \
    $$PWD/ui/js/JsPanelAIHelper.h \
    $$PWD/ui/js/YLJS_LemonLovesBeauty_EditPanel_Helper.h \
    $$PWD/ui/js/YLJS_LemonLovesBeauty_RightPanel_Helper.h

SOURCES+= $$PWD/ui/UI_Btn_Skin.cpp \
    $$PWD/ui/UI_Panel_BtnItemSetting.cpp \
    $$PWD/ui/UIYL_ChatAndCardPanel.cpp \
    $$PWD/ui/UIYL_CommonWordTreeSearchResultWidget.cpp \
    $$PWD/ui/UI_Panel_AddCommonWord.cpp \
    $$PWD/ui/UI_Panel_AddPersonalQuickCommonWord.cpp \
    $$PWD/ui/UI_Panel_ChangeSkin.cpp \
    $$PWD/ui/UI_Panel_HotKey.cpp \
    $$PWD/ui/UI_Panel_LemonLovesBeauty.cpp \
    $$PWD/ui/UI_Panel_ModifyCommonWord.cpp \
    $$PWD/ui/UI_Panel_OutputLog.cpp \
    $$PWD/ui/UI_Panel_PersonalQuickCommonWord.cpp \
    $$PWD/ui/UI_Panel_QuickCommonWord.cpp \
    $$PWD/ui/UI_Panel_RedEnvelopes.cpp \
    $$PWD/ui/UI_Pane_AI_Modify.cpp \
    $$PWD/ui/UI_Pane_AI_SelfBuild.cpp \
    $$PWD/ui/UI_Widget_CommonPhrasesCard_Panel.cpp \
    $$PWD/ui/UI_Widget_CommonWord_Panel.cpp \
    $$PWD/ui/UI_Wnd_AddPersonalQuickCommonWord.cpp \
    $$PWD/ui/UI_Wnd_HotKey.cpp \
    $$PWD/ui/UI_Wnd_ModifyCommonWord.cpp \
    $$PWD/ui/UI_Wnd_OutputLog.cpp \
    $$PWD/ui/UICardDataWidgetPanel.cpp \
    $$PWD/ui/UICardItemData.cpp \
    $$PWD/ui/UI_Pane_NewTab.cpp \
    $$PWD/ui/UI_Widget_AuxiliaryFun_Panenl.cpp \
    $$PWD/ui/UI_Widget_ChatTransfer.cpp \
    $$PWD/ui/UI_Widget_Statistics_BrokenNet_Panel.cpp \
    $$PWD/ui/UI_Widget_Statistics_Panel.cpp \
    $$PWD/ui/Robot/UIEachBotMainWnd.cpp \
    $$PWD/ui/Robot/UIYL_EachbotSettingWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListView.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListViewItemDelegate.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleListViewModel.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListView.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListViewItemDelegate.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultListViewModel.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingUrlWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget_KeyPrompt.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSetting_PreviewEffect_Widget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListView.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListViewItemDelegate.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_ListViewModel.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_SearchResultWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_CountPrompt.cpp \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_KeyPrompt.cpp \
    $$PWD/ui/Robot/YL_ManRobotRuleLeafNodeItemData.cpp \
    $$PWD/ui/Robot/YL_ManRobotRuleListItem.cpp \
    $$PWD/ui/ListView/UIYL_CommonWordListTreeView.cpp \
    $$PWD/ui/ListView/UIYL_CommonWordListViewItemDelegate.cpp \
    $$PWD/ui/ListView/UIYL_CommonWordListViewModel.cpp \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListView.cpp \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListViewItemDelegate.cpp \
    $$PWD/ui/ListView/UI_PersonalQuickCommonWord_ListViewItemModel.cpp \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListView.cpp \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListViewItemDelegate.cpp \
    $$PWD/ui/ListView/UI_QuickCommonWord_ListViewItemModel.cpp \
    $$PWD/ui/TreeView/UI_TreeViewItemDelegate_CommonWord.cpp \
    $$PWD/ui/TreeView/UI_TreeViewItemModel_CommonWord.cpp \
    $$PWD/ui/TreeView/UI_TreeView_CommonWord.cpp \
    $$PWD/ui/UI_Wnd_OutputLog2.cpp \
    $$PWD/ui/js/JsPanelAIHelper.cpp \
    $$PWD/ui/js/YLJS_LemonLovesBeauty_EditPanel_Helper.cpp \
    $$PWD/ui/js/YLJS_LemonLovesBeauty_RightPanel_Helper.cpp

FORMS += $$PWD/ui/UI_Panel_BtnItemSetting.ui \
    $$PWD/ui/UIYL_ChatAndCardPanel.ui \
    $$PWD/ui/UIYL_CommonWordTreeSearchResultWidget.ui \
    $$PWD/ui/UI_Panel_AddCommonWord.ui \
    $$PWD/ui/UI_Panel_AddPersonalQuickCommonWord.ui \
    $$PWD/ui/UI_Panel_ChangeSkin.ui \
    $$PWD/ui/UI_Panel_HotKey.ui \
    $$PWD/ui/UI_Panel_LemonLovesBeauty.ui \
    $$PWD/ui/UI_Panel_ModifyCommonWord.ui \
    $$PWD/ui/UI_Panel_OutputLog.ui \
    $$PWD/ui/UI_Panel_PersonalQuickCommonWord.ui \
    $$PWD/ui/UI_Panel_QuickCommonWord.ui \
    $$PWD/ui/UI_Panel_RedEnvelopes.ui \
    $$PWD/ui/UI_Pane_AI_Modify.ui \
    $$PWD/ui/UI_Pane_AI_SelfBuild.ui \
    $$PWD/ui/UI_Widget_CommonPhrasesCard_Panel.ui \
    $$PWD/ui/UI_Widget_CommonWord_Panel.ui \
    $$PWD/ui/UI_Wnd_AddPersonalQuickCommonWord.ui \
    $$PWD/ui/UI_Wnd_HotKey.ui \
    $$PWD/ui/UI_Wnd_ModifyCommonWord.ui \
    $$PWD/ui/UI_Wnd_OutputLog.ui \
    $$PWD/ui/UI_Wnd_OutputLog2.ui \
    $$PWD/ui/UICardDataWidgetPanel.ui \
    $$PWD/ui/UICardItemData.ui \
    $$PWD/ui/UI_Pane_NewTab.ui \
    $$PWD/ui/UI_Widget_AuxiliaryFun_Panenl.ui \
    $$PWD/ui/UI_Widget_ChatTransfer.ui \
    $$PWD/ui/UI_Widget_Statistics_BrokenNet_Panel.ui \
    $$PWD/ui/UI_Widget_Statistics_Panel.ui \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_KeyPrompt.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSearchResultWidget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSetting_PreviewEffect_Widget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingUrlWidget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRuleSettingWidget_KeyPrompt.ui \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotSettingWidget_CountPrompt.ui \
    $$PWD/ui/Robot/UIEachBotMainWnd.ui \
    $$PWD/ui/Robot/UIYL_EachbotSettingWidget.ui \
    $$PWD/ui/Robot/UIYL_ManRobotRule_KeyWord_SearchResultWidget.ui
