#ifndef PLAT_INTERFACE_GLOBAL_H
#define PLAT_INTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAT_INTERFACE_LIBRARY)
#  define PLAT_INTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define PLAT_INTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAT_INTERFACE_GLOBAL_H
