SOURCES += \
    $$PWD/ui/UIYL_BaseWnd.cpp \
    $$PWD/ui/UI_Widget_User_Panel.cpp \
    $$PWD/ui/UI_Widget_MainWindow.cpp \
    $$PWD/ui/common/UI_WebWidget.cpp \
    $$PWD/ui/common/UIYL_TopMenuFunPanel.cpp \
    $$PWD/ui/common/AddressLibrary_Helper.cpp \
    $$PWD/ui/common/uiiewnd.cpp \
    $$PWD/ui/common/uinotifymessagebox.cpp \
    $$PWD/ui/Common/BaseMainWnd.cpp \
    $$PWD/ui/Common/UI_Wnd_MessageBox.cpp \
    $$PWD/ui/Common/uimenubutton.cpp \
    $$PWD/ui/Common/UISearchCBox.cpp \
    $$PWD/ui/Common/UITextEdit.cpp \
    $$PWD/ui/Common/UIYL_RichTextPanel.cpp \
    $$PWD/ui/Common/UIPictureWidgetPanel.cpp \
    $$PWD/ui/Common/UIStatusWidgetPanel.cpp \
    $$PWD/ui/Common/UI_Widget_Lock.cpp \
    $$PWD/ui/Common/UI_CommPanel_Notice.cpp \
    $$PWD/ui/Common/UI_NoticeBubblePrompt.cpp \
    $$PWD/ui/Common/el_textedit.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_data.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_addtag_widget.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listview.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_delegate.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_model.cpp \
    $$PWD/ui/common/summarytag/content/ui_summarytag_pushbutton.cpp \
    $$PWD/ui/common/summarytag/ui_summarytag_combobox.cpp \
    $$PWD/ui/common/summarytag/ui_summarytag_combobox_widget.cpp \
    $$PWD/ui/Common/UICommonWidgetPanel.cpp \
    $$PWD/ui/Common/UI_CommonWnd.cpp \
    $$PWD/ui/Common/uilockwnd.cpp \
    $$PWD/ui/Common/uiunlockwnd.cpp \
    $$PWD/ui/Common/JsCommonHelper.cpp \
    $$PWD/ui/Common/UI_WebView_ShieldBackSpace.cpp \
    $$PWD/ui/Common/BaseJsCommHelper.cpp \
    $$PWD/ui/Common/JsWebWidgetHelp.cpp \
    $$PWD/ui/common/utilsviewhelper.cpp \
    $$PWD/ui/js/JsPanelNewTabHelper.cpp \
    $$PWD/ui/js/JsNoticeHelper.cpp \
    $$PWD/ui/js/JsChatRichEditHelper.cpp

HEADERS += \
    $$PWD/ui/UIYL_BaseWnd.h \    
    $$PWD/ui/UI_Widget_User_Panel.h \
    $$PWD/ui/UI_Widget_MainWindow.h \
    $$PWD/ui/common/UI_WebWidget.h \
    $$PWD/ui/common/JsWebWidgetHelp.h \
    $$PWD/ui/common/UIYL_TopMenuFunPanel.h \
    $$PWD/ui/common/AddressLibrary_Helper.h \
    $$PWD/ui/common/uiiewnd.h \
    $$PWD/ui/common/uinotifymessagebox.h \
    $$PWD/ui/Common/BaseMainWnd.h \
    $$PWD/ui/Common/UI_Wnd_MessageBox.h \
    $$PWD/ui/Common/uimenubutton.h \
    $$PWD/ui/Common/UISearchCBox.h \
    $$PWD/ui/Common/UITextEdit.h \
    $$PWD/ui/Common/UIYL_RichTextPanel.h \
    $$PWD/ui/Common/UIPictureWidgetPanel.h \
    $$PWD/ui/Common/UIStatusWidgetPanel.h \
    $$PWD/ui/Common/UI_Widget_Lock.h \
    $$PWD/ui/Common/UI_CommPanel_Notice.h \
    $$PWD/ui/Common/UI_NoticeBubblePrompt.h \
    $$PWD/ui/Common/el_textedit.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_data.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_addtag_widget.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listview.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_delegate.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_listviewitem_model.h \
    $$PWD/ui/common/summarytag/content/ui_summarytag_pushbutton.h \
    $$PWD/ui/common/summarytag/ui_summarytag_combobox.h \
    $$PWD/ui/common/summarytag/ui_summarytag_combobox_widget.h \
    $$PWD/ui/Common/UICommonWidgetPanel.h \
    $$PWD/ui/Common/UI_CommonWnd.h \
    $$PWD/ui/Common/uilockwnd.h \
    $$PWD/ui/Common/uiunlockwnd.h \
    $$PWD/ui/Common/JsCommonHelper.h \
    $$PWD/ui/Common/UI_WebView_ShieldBackSpace.h \
    $$PWD/ui/Common/BaseJsCommHelper.h \
    $$PWD/ui/Common/JsWebWidgetHelp.h \
    $$PWD/ui/common/utilsviewhelper.h \
    $$PWD/ui/js/JsPanelNewTabHelper.h \
    $$PWD/ui/js/JsNoticeHelper.h \
    $$PWD/ui/js/JsChatRichEditHelper.h

FORMS += \
    $$PWD/ui/common/UI_WebWidget.ui \
    $$PWD/ui/common/UIYL_TopMenuFunPanel.ui \
    $$PWD/ui/common/uiiewnd.ui \
    $$PWD/ui/common/uinotifymessagebox.ui \
    $$PWD/ui/common/baseMainWnd.ui \
    $$PWD/ui/UI_Widget_User_Panel.ui \
    $$PWD/ui/Common/UI_Wnd_MessageBox.ui \
    $$PWD/ui/UI_Widget_MainWindow.ui \
    $$PWD/ui/Common/uimenubutton.ui \
    $$PWD/ui/Common/UIYL_RichTextPanel.ui \
    $$PWD/ui/Common/UIPictureWidgetPanel.ui \
    $$PWD/ui/Common/UIStatusWidgetPanel.ui \
    $$PWD/ui/Common/UI_Widget_Lock.ui \
    $$PWD/ui/Common/UI_CommPanel_Notice.ui \
    $$PWD/ui/Common/UI_NoticeBubblePrompt.ui \
    $$PWD/ui/Common/uilockwnd.ui \
    $$PWD/ui/Common/uiunlockwnd.ui \
    $$PWD/ui/Common/el_textedit.ui \
    $$PWD/ui/Common/UICommonWidgetPanel.ui \
    $$PWD/ui/Common/UI_CommonWnd.ui \
    $$PWD/ui/Common/SummaryTag/UI_SummaryTag_ComboBox_Widget.ui \
    $$PWD/ui/Common/SummaryTag/Content/UI_SummaryTag_AddTag_Widget.ui
