# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
# message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += \
    $$PWD/outdataconsolework.h \
    $$PWD/OutDataConsoleAgent.h \
    $$PWD/LogConsoleAgent.h \
    $$PWD/ConstStringHelper.h \
    $$PWD/FBDataCenterAgent.h \
    $$PWD/RequestReTryProcess.h \
    $$PWD/RMAgent.h \
    $$PWD/RequestKeepLive.h \
    $$PWD/KillProcessHelper.h \
    $$PWD/IRequest.h \
    $$PWD/IAgent.h \
    $$PWD/WorkThread.h \
    $$PWD/logconsolework.h

SOURCES += \
    $$PWD/outdataconsolework.cpp \
    $$PWD/OutDataConsoleAgent.cpp \
    $$PWD/LogConsoleAgent.cpp \
    $$PWD/ConstStringHelper.cpp \
    $$PWD/FBDataCenterAgent.cpp \
    $$PWD/IAgent.cpp \
    $$PWD/IRequest.cpp \
    $$PWD/KillProcessHelper.cpp \
    $$PWD/RequestKeepLive.cpp \
    $$PWD/RequestReTryProcess.cpp \
    $$PWD/RMAgent.cpp \
    $$PWD/WorkThread.cpp \
    $$PWD/logconsolework.cpp
