#ifndef ROUTERMONITOR_GLOBAL_H
#define ROUTERMONITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ROUTERMONITOR_LIBRARY)
#  define ROUTERMONITOR_EXPORT Q_DECL_EXPORT
#else
#  define ROUTERMONITOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ROUTERMONITOR_GLOBAL_H
