#ifndef PLAT_CONTROLL_GLOBAL_H
#define PLAT_CONTROLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLAT_CONTROLL_LIBRARY)
#  define PLAT_CONTROLL_EXPORT Q_DECL_EXPORT
#else
#  define PLAT_CONTROLL_EXPORT Q_DECL_IMPORT
#endif

#endif // PLAT_CONTROLL_GLOBAL_H
