# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
# message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += $$PWD/data/GlobalConfig.h \
    $$PWD/data/CommInfo.h \
    $$PWD/protocol/IResponse.h \
    $$PWD/protocol/IRequest.h \
    $$PWD/lib_json/json_reader.h \
    $$PWD/lib_json/json_value.h \
    $$PWD/lib_json/json_writer.h \
    $$PWD/utils/BaseConstructionData.h \
    $$PWD/utils/UISingleton.h \
     $$PWD/utils/UISubject.h \
    $$PWD/utils/targetver.h \
    $$PWD/utils/ConstStringHelper.h \
     $$PWD/utils/DefineHelper.h \
    $$PWD/utils/UIObserver.h \
    $$PWD/utils/utilshelper.h \
    $$PWD/utils/jsonhelper.h \
        $$PWD/el_common_global.h \
        $$PWD/el_Common.h


	
SOURCES += $$PWD/data/GlobalConfig.cpp \
    $$PWD/data/CommInfo.cpp \
    $$PWD/protocol/IResponse.cpp \
    $$PWD/protocol/IRequest.cpp \
    $$PWD/lib_json/json_reader.cpp \
    $$PWD/lib_json/json_value.cpp \
    $$PWD/lib_json/json_writer.cpp \
    $$PWD/utils/BaseConstructionData.cpp \
    $$PWD/utils/ConstStringHelper.cpp \
    $$PWD/utils/jsonhelper.cpp \
    $$PWD/el_Common.cpp


msvc{    
    HEADERS +=$$PWD/utils/BasicExcelVC6.hpp \
    $$PWD/utils/excelhelper.h
    SOURCES += $$PWD/utils/BasicExcelVC6.cpp \
    $$PWD/utils/excelhelper.cpp

}
